using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;

public class UIPopupManager : MonoBehaviour
{
    public GameObject popupPanel;
    public Text popupText;
    public Image popupImage;
    public Camera arCamera;

    // Yapı isimlerine göre gösterilecek metinler
    private Dictionary<string, string> structureDescriptions = new Dictionary<string, string>
    {
        { "uae", "🕋 Kâbe Nedir?\r\nKâbe, İslam dininin en kutsal yapısıdır. Suudi Arabistan'ın Mekke şehrinde, Mescid-i Haram (Harem-i Şerif) adlı büyük caminin tam ortasında yer alır. Müslümanlar, Kâbe’ye yönelerek namaz kılarlar (kıble) ve ömürlerinde bir kez hac ibadeti yapmakla yükümlüdürler.\r\n\r\n📌 Kâbe'nin Temel Özellikleri\r\nÖzellik\tAçıklama\r\nKonum\tMekke, Suudi Arabistan\r\nYapıldığı Malzeme\tTaş ve mermer\r\nYükseklik\tYaklaşık 13,1 metre\r\nYüzey Ölçüsü\t12 m x 10 m dikdörtgen prizma\r\nKapısı\tAltın kaplama, yerden 2 metre yüksektedir\r\nÖrtüsü (Kisve)\tSiyah ipek kumaş, altın işlemelerle bezenmiştir\r\nİç Yapısı\tİçeride üç ahşap sütun, gümüş kandiller bulunur\r\n\r\n🕰️ Tarihçesi\r\n1. İlk Yapılışı\r\nİslam inancına göre Kâbe, ilk olarak Hz. Âdem tarafından yapılmıştır.\r\n\r\nDaha sonra Hz. İbrahim ve oğlu Hz. İsmail tarafından bugünkü temelleriyle yeniden inşa edilmiştir (yaklaşık M.Ö. 2000’li yıllar).\r\n\r\n2. İslam’dan Önce\r\nKâbe, İslam’dan önce putlarla doluydu ve Arap kabileleri tarafından ziyaret edilirdi.\r\n\r\n360’tan fazla put yerleştirilmişti.\r\n\r\n3. İslam Dönemi\r\nHz. Muhammed, hicretten sonra 630 yılında Mekke’yi fethetti ve Kâbe'deki putları temizledi.\r\n\r\nKıble, önce Kudüs'tü; daha sonra Kâbe’ye çevrildi (Bakara Suresi, 144. ayet)." },
        { "india", "🕌 Tâc Mahal Nedir?\r\nTâc Mahal, Hindistan’ın Agra şehrinde bulunan, beyaz mermerden yapılmış dünyaca ünlü bir anıt mezardır. 17. yüzyılda, Babür İmparatoru Şah Cihan, çok sevdiği eşi Mümtaz Mahal için yaptırmıştır. Hem aşkın hem mimarinin sembolüdür ve UNESCO Dünya Mirası Listesindedir.\r\n\r\n📌 Tâc Mahal'in Temel Bilgileri\r\nÖzellik\tAçıklama\r\nYer\tAgra, Hindistan\r\nYapım Tarihi\t1632 – 1653 yılları arası\r\nYaptıran\tBabür İmparatoru Şah Cihan\r\nMimar\tUsta İsa Efendi (İstanbul'dan gittiği söylenir) ve ekibi\r\nYapım Süresi\t21 yıl\r\nYapı Malzemesi\tBeyaz mermer, değerli taşlar\r\nMimari Tarz\tİslam, Türk, Hint ve İran mimarisi karışımı\r\n\r\n❤️ Yapılış Amacı: Bir Aşk Hikayesi\r\nŞah Cihan’ın eşi Mümtaz Mahal, 14. çocuğunu doğururken vefat etti (1631).\r\n\r\nŞah Cihan, onun anısını yaşatmak için dünyanın en güzel türbesini yaptırmaya karar verdi.\r\n\r\nTâc Mahal, Mümtaz Mahal’in mezarını barındıran büyük bir aşk anıtıdır.\r\n\r\n\U0001f9f1 Mimari Özellikleri\r\nDış Yapı\r\nTamamen beyaz mermerden yapılmıştır.\r\n\r\n73 metre yüksekliğindedir.\r\n\r\nDört köşesinde 40 metrelik minareler vardır.\r\n\r\nÖnünde yansıma havuzları olan geniş bir bahçe yer alır (Cennet bahçesini simgeler).\r\n\r\nİç Kısım\r\nİçeride Mümtaz Mahal ve Şah Cihan’ın sandukaları (sembolik mezarları) vardır.\r\n\r\nGerçek mezarları, alt kattaki mezar odasında yer alır.\r\n\r\nSüslemeler\r\nDuvarlarında ayetler, çiçek motifleri ve değerli taşlarla yapılmış işlemeler bulunur.\r\n\r\nKullanılan taşlar: Yakut, zümrüt, akik, lal, sedef vb.\r\n\r\n🏗️ Yapım Detayları\r\nYaklaşık 20.000 işçi çalıştı.\r\n\r\nMalzemeler Hindistan’ın farklı bölgelerinden ve Orta Asya’dan getirildi.\r\n\r\nMermerler Rajasthan, değerli taşlar Çin, İran, Tibet ve Osmanlı topraklarından getirildi.\r\n\r\n🌍 Kültürel ve Tarihî Önemi\r\n1983 yılında UNESCO Dünya Mirası Listesine alındı.\r\n\r\nDünyanın Yedi Yeni Harikası arasında yer alır (2007’de seçildi)." },
        { "turkiye", "🏛️ Anıtkabir Nedir?\r\nAnıtkabir, Türkiye Cumhuriyeti’nin kurucusu Mustafa Kemal Atatürk’ün anıt mezarıdır. Ankara’da yer alır ve hem bir mezar hem de anıtsal yapı olarak, Türkiye’nin en önemli sembollerinden biridir.\r\n\r\n📌 Anıtkabir’in Temel Bilgileri\r\nÖzellik\tAçıklama\r\nYer\tTandoğan, Ankara, Türkiye\r\nYapım Tarihi\t1944 – 1953\r\nAçılış Tarihi\t10 Kasım 1953\r\nMimari Tarz\tAnıtsal, simetrik, sade ve etkileyici\r\nMimarlar\tProf. Emin Onat ve Doç. Orhan Arda\r\nYükseklik\tŞeref Salonu: 17 m; platform yüksekliği: 907 m\r\nToplam Alan\tYaklaşık 750.000 m²\r\n\r\n👷‍♂️ Yapım Süreci\r\n1938’de Atatürk’ün vefatından sonra, geçici olarak Etnografya Müzesi’nde defnedildi.\r\n\r\n1941’de yapılan yarışma sonucunda mimari proje belirlendi.\r\n\r\n1944’te inşaata başlandı ve 1953 yılında tamamlandı.\r\n\r\nAynı yıl, Atatürk’ün naaşı büyük bir törenle Anıtkabir’e nakledildi.\r\n\r\n🏞️ Anıtkabir’in Bölümleri\r\n1. Aslanlı Yol\r\n262 metre uzunluğunda bir yürüyüş yoludur.\r\n\r\nYolun iki yanında aslan heykelleri vardır (Hitit kültüründen esinlenilmiş).\r\n\r\nZiyaretçiyi anıta hazırlar; saygı duygusu uyandırır.\r\n\r\n2. Tören Meydanı\r\n15.000 kişi kapasiteli geniş meydandır.\r\n\r\nDevlet törenleri burada yapılır.\r\n\r\n3. Şeref Salonu\r\nAtatürk’ün mozolesinin (sembolik mezar) bulunduğu ana salondur.\r\n\r\nDuvarları traverten taşla kaplıdır.\r\n\r\nTam altında gerçek mezar odası yer alır.\r\n\r\n4. Mezar Odası\r\nSadece özel ziyaretlerde açılır.\r\n\r\nAtatürk’ün naaşı, kırmızı mermer lahit taşının altındaki bu odadadır.\r\n\r\n5. Müze ve Sergi Alanları\r\nAtatürk'ün eşyaları, Nutuk, giysileri ve Kurtuluş Savaşı’na ait belgeler sergilenir.\r\n\r\nKurtuluş Savaşı Müzesi de bu alanlarda yer alır.\r\n\r\n🇹🇷 Anlam ve Sembolizm\r\nYapının her ayrıntısı Türk milletinin bağımsızlık ve birlik duygusunu yansıtır.\r\n\r\nOn kule, Türk milletinin tarihindeki on önemli özelliği simgeler:\r\n\r\nBağımsızlık Kulesi" },
        { "china", "🏠 Çin Evi Mimarisi Nedir?\r\nÇin evi mimarisi, Çin'in geleneksel kültürünü, felsefesini (özellikle Konfüçyüsçülüğü ve Feng Shui'yi) ve sosyal yapısını yansıtan bir mimari tarzdır. Bu mimari, yüzyıllar boyunca gelişmiş ve bölgesel farklılıklar taşısa da bazı ortak özellikler gösterir.\r\n\r\n📌 Temel Özellikler\r\nÖzellik\tAçıklama\r\nSimetri\tBinalar genellikle mutlak simetri üzerine kuruludur.\r\nİç Avlu (Siheyuan)\tMerkezi bir avlu (courtyard) etrafında odalar yerleştirilir.\r\nMalzeme\tAhşap ana yapı malzemesidir; kiremit, toprak ve taş da kullanılır.\r\nÇatılar\tYüksek eğimli, yukarı doğru kıvrık köşelidir (ejderha gibi durur).\r\nFeng Shui\tYapılar doğal enerji akışına (Qi) göre tasarlanır.\r\nRenkler\tGenellikle kırmızı (uğur) ve sarı (imparatorluk) renkleri kullanılır.\r\nDuvarlar\tDış duvarlar yüksek ve kapalıdır; mahremiyet ön plandadır.\r\n\r\n🏯 Ünlü Çin Evi Mimarisi Türleri\r\n1. Siheyuan (四合院) – Avlulu Ev\r\nPekin başta olmak üzere kuzey Çin’de yaygındır.\r\n\r\nDört tarafı odalarla çevrili bir iç avludan oluşur.\r\n\r\nAile düzenini ve hiyerarşiyi temsil eder.\r\n\r\n2. Tulou (土楼) – Toprak Evler\r\nGüneydoğu Çin’de (Fujian eyaleti) görülür.\r\n\r\nYuvarlak ya da kare şekilli, çok katlı büyük yapılardır.\r\n\r\nBirden çok aileye ev sahipliği yapar; savunma amaçlı inşa edilmiştir.\r\n\r\n3. Yaodong (窑洞) – Mağara Evler\r\nKuzeybatı Çin’de (Shaanxi) yaygındır.\r\n\r\nTepenin içine oyulmuş mağara benzeri evlerdir; yazın serin, kışın sıcak olur.\r\n\r\n4. Diaojiaolou (吊脚楼) – Sütun Üzerinde Evler\r\nGüney Çin'in dağlık bölgelerinde yaşayan etnik azınlıklarda görülür.\r\n\r\nAhşap direkler üzerine kurulu, genellikle su kenarında yer alan yapılardır.\r\n\r\n\U0001f9f1 Mimari Unsurlar\r\nÇatı Tarzları:\r\n\r\nİki yana eğimli çatı (xie shan)\r\n\r\nÇok katlı çatılar (pagoda tarzı)\r\n\r\nYukarı kıvrık köşeler, kötü ruhları uzaklaştırmak için semboliktir.\r\n\r\nKapılar:" },
        { "italy", "🏛️ Pisa Kulesi Nedir?\r\nPisa Kulesi, İtalya’nın Toskana bölgesinde, Pisa şehrinde yer alan ünlü eğik çan kulesidir. Orijinal adı: Torre Pendente di Pisa (Eğik Pisa Kulesi).\r\nKatolik bir katedralin parçası olan kule, aslında bir çan kulesi (campanile) olarak inşa edilmiştir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Konum\tPisa, İtalya\r\n🏗️ Yapım Başlangıcı\t1173\r\n🏁 Tamamlanma\t1372 (yaklaşık 200 yıl sürdü)\r\n🏛️ Mimari Tarz\tRomanesk (Roma sonrası Avrupa mimarisi)\r\n📐 Yükseklik\tYaklaşık 56 metre\r\n\U0001f9f1 Malzeme\tBeyaz mermer ve kireçtaşı\r\n🎯 Eğimi\tYaklaşık 4 derece (orijinalde 5.5 dereceye yakındı)\r\n🛎️ İşlevi\tÇan kulesi (katedralin parçası)\r\n\r\n🕰️ Tarihçesi\r\n1. İnşaatın Başlaması (1173)\r\nKulenin temeli 1173’te atıldı.\r\n\r\nkat yapılırken kule, yumuşak zemin nedeniyle eğilmeye başladı.\r\n\r\nBu nedenle inşaat uzun yıllar durduruldu.\r\n\r\n2. Tamamlanma (14. yüzyıl)\r\n1272–1372 yılları arasında yavaş yavaş tamamlandı.\r\n\r\nMimarlar eğimi dengelemek için üst katları daha kısa yaptı.\r\n\r\n3. Eğimin Artması ve Düzeltme Çabaları\r\nYüzyıllar boyunca eğilmeye devam etti.\r\n\r\n1990’da kule kapatıldı ve eğimi azaltmak için zemin mühendisliği çalışmaları yapıldı.\r\n\r\nBugün eğimi durağan hale getirildi, yani artık artmıyor.\r\n\r\n\U0001f9ed Neden Eğildi?\r\nKule, kum, kil ve deniz çamurundan oluşan yumuşak bir zemine inşa edildi.\r\n\r\nBu zemin, ağır yapıyı taşıyamadı ve kule sola doğru eğilmeye başladı.\r\n\r\nTemel derinliği yalnızca 3 metre olduğundan yeterince sağlam değildi.\r\n\r\n🛎️ Mimari Özellikleri\r\n8 katlı bir yapıdır (altı sütunlu galeri + çan katı).\r\n\r\n294 basamak ile zirveye çıkılır.\r\n\r\nMimari süslemeleri klasik Roma tarzında sütunlar, kemerler ve oyma desenlerdir.\r\n\r\n🎓 Galileo ve Pisa Kulesi\r\nEfsaneye göre, bilim insanı Galileo Galilei, buradan farklı kütlelerdeki cisimleri düşürerek yerçekimi deneyleri yapmıştır." },
        { "spain", "⛪ La Sagrada Família Nedir?\r\nLa Sagrada Família (Kutsal Aile Bazilikası), İspanya'nın Barselona şehrinde yer alan, dünyaca ünlü bir Roma Katolik kilisesidir. Yapımı halen devam etmektedir ve mimari açıdan en uzun süredir inşa edilen yapılardan biridir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Konum\tBarselona, Katalonya, İspanya\r\n🏗️ Yapım Başlangıcı\t1882\r\n👷‍♂️ Mimar\tBaşlangıçta Francisco de Paula del Villar, sonra Antoni Gaudí\r\n🎨 Tarz\tGotik + Art Nouveau (Modernist) + Gaudí’nin özgün stili\r\n🏁 Tahmini Bitiş\t2026 (Atatürk ve Gaudí’nin ölümünün 100. yılı)\r\n⛪ Statü\tBazilika (Papa XVI. Benedictus tarafından 2010’da kutsandı)\r\n\U0001f9f1 Malzeme\tTaş, beton, seramik, cam, mozaik\r\n\r\n\U0001f9d1‍🎨 Mimar: Antoni Gaudí\r\nKatalan mimar Antoni Gaudí, 1883’te projeyi devraldı.\r\n\r\nHayatının son 15 yılını sadece bu yapıya adadı.\r\n\r\nGaudí’nin ölümü (1926) sonrası, projeyi takip eden mimarlar onun çizimlerine göre çalışmaya devam etti.\r\n\r\nGaudí’nin vizyonu: Doğa, dindarlık ve geometriyi birleştiren mimari.\r\n\r\n\U0001f9f1 Mimari Özellikler\r\n🕍 Kuleler\r\nToplamda 18 kule olacak:\r\n\r\n12’si havariler için\r\n\r\n4’ü İncil yazarları için\r\n\r\n1’i Meryem Ana için\r\n\r\n1’i İsa Mesih için (172,5 m – tamamlandığında Barselona’daki en yüksek yapı olacak)\r\n\r\n🎭 Cepheler\r\nDoğuş Cephesi (Nativity Façade)\r\n\r\nGaudí döneminde yapıldı\r\n\r\nİsa'nın doğumunu anlatır\r\n\r\nAyrıntılı süslemeler ve doğal formlar içerir\r\n\r\nTutku Cephesi (Passion Façade)\r\n\r\nDaha sade ve keskin çizgilidir\r\n\r\nİsa'nın çarmıha gerilişini anlatır\r\n\r\nYüceliş Cephesi (Glory Façade)\r\n\r\nHenüz tamamlanmamıştır\r\n\r\nİsa'nın dirilişi ve cennet tasviri olacak\r\n\r\n🌈 İç Mekan\r\nRenkli vitraylar, doğal ışık oyunlarıyla büyüleyici bir atmosfer yaratır.\r\n\r\nSütunlar ağaç dalları gibi yukarı doğru yayılır (doğadan esinlenilmiştir)." },
        { "mexico", "🗿 Kukulcán Piramidi Nedir?\r\nKukulcán Piramidi, Meksika’da yer alan antik Maya şehri Chichén Itzá’da bulunan, Maya medeniyetine ait bir tapınaktır.\r\nAynı zamanda El Castillo (İspanyolca \"kale\") olarak da bilinir.\r\n\r\nBu yapı, Maya tanrısı Kukulcán’a (tüylü yılan tanrı) adanmıştır ve hem mimari hem astronomik özellikleriyle büyüleyicidir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Konum\tChichén Itzá, Yucatán Yarımadası, Meksika\r\n🏗️ İnşa Dönemi\tM.S. 9–12. yüzyıllar arası\r\n\U0001f6d5 Uygarlık\tAntik Maya Medeniyeti\r\n\U0001f9f1 Malzeme\tKireçtaşı\r\n📐 Yükseklik\tYaklaşık 30 metre (tapınak dahil)\r\n\U0001f9ee Basamak Sayısı\tToplamda 365 basamak (güneş yılı kadar)\r\n🎯 Fonksiyon\tTapınak + astronomik gözlem noktası\r\n🐍 Adanmış Olduğu Tanrı\tKukulcán (tüylü yılan tanrısı, Azteklerde Quetzalcoatl)\r\n\r\n\U0001f9e0 Mimari Özellikleri\r\n\U0001fa9c Basamaklar\r\nPiramidin 4 tarafında 91 basamak vardır.\r\n\r\nÜstteki platformla birlikte toplam 365 eder → Güneş yılıyla birebir!\r\n\r\n\U0001f9ca Katmanlar\r\n9 büyük katmanı vardır → Maya kozmolojisinde 9 yeraltı dünyası simgelenir.\r\n\r\n\U0001f6d5 Üst Tapınak\r\nZirvede küçük bir tapınak bulunur.\r\n\r\nBurada tanrılara adaklar sunulurdu.\r\n\r\n🌞 Güneş ve Gölge Oyunu (Ekinoks Fenomeni)\r\nHer yıl ilkbahar ve sonbahar ekinokslarında (21 Mart ve 21 Eylül civarı):\r\n\r\n☀️ Güneşin konumu sayesinde, piramidin kuzey merdiveninde oluşan ışık ve gölgeler, yılanın vücudu gibi görünür.\r\n\r\nGölgeyle oluşan zikzak şekiller, tapınağın baş kısmındaki yılan başıyla birleşir.\r\n\r\nBu olay, tanrı Kukulcán’ın yeryüzüne inişi olarak yorumlanır.\r\n\r\nBu muhteşem doğa ve mühendislik olayı binlerce turistin her yıl Meksika’ya akın etmesini sağlar.\r\n\r\n🐍 Kukulcán Kimdir?\r\nKukulcán, Maya mitolojisinde tüylü yılan tanrıdır.\r\n\r\nBilgelik, gökyüzü, tarım, medeniyet gibi kavramlarla ilişkilidir." },
        { "egypt", "🏜️ Mısır Piramitleri Nedir?\r\nMısır Piramitleri, antik Mısır medeniyeti tarafından yaklaşık 4.500 yıl önce inşa edilmiş dev mezar yapılarıdır.\r\nÖzellikle firavunlar ve soylular için yapılmışlardır.\r\nDünyanın en eski ve en gizemli yapıları arasında yer alırlar.\r\n\r\n📌 Genel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Konum\tEn çok bilinenler: Gize (Kahire yakınlarında)\r\n🏗️ İnşa Dönemi\tM.Ö. 2700 – 1700 arası (Eski ve Orta Krallık dönemleri)\r\n⚱️ Amaç\tFiravunların mezarı ve ölümsüzlük sembolü\r\n\U0001f9f1 Malzeme\tKireçtaşı, granit, bazen altın kaplama\r\n\U0001f6d5 En Ünlü Piramitler\tKeops (Khufu), Kefren (Khafre), Mikerinos (Menkaure)\r\n\U0001f9ed Yönleri\tDört yüzü tam olarak ana yönlere (kuzey, güney, doğu, batı) bakar\r\n\r\n🏛️ Gize Piramitleri (Dünyanın Yedi Harikasından Biri)\r\n1. 🏯 Keops Piramidi (Büyük Piramit)\r\nM.Ö. 2580 civarında inşa edildi.\r\n\r\nFiravun Khufu (Keops) için yapıldı.\r\n\r\nYükseklik: 146.6 metreydi (bugün 138 m).\r\n\r\nYaklaşık 2,3 milyon taş bloktan oluşur (her biri ortalama 2.5 ton!).\r\n\r\n2. 🏯 Kefren Piramidi\r\nKeops'un oğlu Khafre (Kefren) için yapıldı.\r\n\r\nHemen önünde dev Büyük Sfenks heykeli vardır.\r\n\r\n3. 🏯 Mikerinos Piramidi\r\nDaha küçük boyutludur (yaklaşık 66 metre).\r\n\r\nMikerinos (Menkaure) firavunu için yapılmıştır.\r\n\r\n🎯 Mısır Piramitlerinin Özellikleri\r\n\U0001f9ed Astronomik Konum\r\nPiramitlerin yönleri tam olarak dört ana yöne bakar.\r\n\r\nKeops Piramidi, coğrafi kuzeye en hassas hizalanmış antik yapıdır.\r\n\r\n\U0001f9f1 İnşaat Yöntemi\r\nHalen tartışılan bir konudur.\r\n\r\nTaş bloklar muhtemelen:\r\n\r\nRampa sistemleri\r\n\r\nKaldıraçlar\r\n\r\nBinlerce işçiyle (köle değil, maaşlı işçiler) taşındı\r\n\r\n🎨 Kaplama Taşları\r\nDış yüzeyi zamanında beyaz cilalı kireçtaşıyla kaplıydı.\r\n\r\nParlak yüzey, güneşte parlayan dev bir yapı gibi görünmesini sağlardı.\r\n\r\n\U0001f9e0 Mısır Piramitleri Neden Yapıldı?" },
        { "usa", "🗽 Özgürlük Heykeli Nedir?\r\nÖzgürlük Heykeli (Statue of Liberty), Amerika Birleşik Devletleri’nin bağımsızlık ve özgürlük sembolüdür.\r\nNew York Limanı’ndaki Liberty Island (Özgürlük Adası)’nda yer alır ve ABD’ye gelen göçmenler için “özgürlüğe hoş geldiniz” mesajı taşır.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Konum\tLiberty Island, New York, ABD\r\n🎁 Kim Hediye Etti?\tFransa, ABD’ye 100. bağımsızlık yılı için (1886)\r\n\U0001f9d1‍🎨 Tasarımcı\tHeykel: Frédéric Auguste Bartholdi\r\n\U0001f9f1 İç iskelet tasarımı\tGustave Eiffel (Eiffel Kulesi’nin mühendisi)\r\n🏗️ Tamamlanma Yılı\t1886\r\n🗽 Boyu\tKaide dahil 93 metre (heykelin kendisi 46 metre)\r\n⚖️ Ağırlık\tYaklaşık 225 ton\r\n🗽 Yapım Malzemesi\tBakır (dış katman), çelik (iç yapı)\r\n\r\n🔍 Heykelin Simgeleri ve Anlamı\r\n👑 Başındaki taç:\r\n7 sivri uç → 7 kıta ve 7 denizi simgeler → evrensel özgürlük\r\n\r\n🔥 Elindeki meşale:\r\nAydınlanma, umut, özgürlüğün ışığı\r\n\r\n📜 Diğer elindeki tablet:\r\nÜzerinde “JULY IV MDCCLXXVI” yazılı → ABD’nin Bağımsızlık Günü (4 Temmuz 1776)\r\n\r\n⛓️ Ayaklarının altındaki kırık zincirler:\r\nTiranlık ve kölelikten kurtuluş anlamına gelir\r\n\r\n🛠️ Nasıl Yapıldı?\r\nHeykel parçalar hâlinde Fransa’da üretildi.\r\n\r\n350’den fazla parçaya bölündü.\r\n\r\nBir Fransız gemisiyle New York’a taşındı (1885).\r\n\r\nABD’liler kaideyi inşa etmek için bağış kampanyası düzenledi.\r\n\r\n1886’da büyük törenle açıldı.\r\n\r\n🗽 Özgürlük Heykeli'nin Önemi\r\nAmerika’ya gelen göçmenler için bir umut simgesi oldu.\r\n\r\nyüzyıl başlarında limandan geçen göçmen gemileri ilk onu görürdü.\r\n\r\nKadın figürü, Libertas adında Roma özgürlük tanrıçasını temsil eder.\r\n\r\n🎯 UNESCO ve Turizm\r\n1984 yılında UNESCO Dünya Mirası Listesi’ne alındı.\r\n\r\nHer yıl milyonlarca turist ziyaret eder.\r\n\r\nHeykelin içinden taç kısmına kadar çıkılabilir (önceden rezervasyon gerekir)." },
        { "iran", "🏛️ Azadi Kulesi Nedir?\r\nAzadi Kulesi (İranca: برج آزادی, Borj-e Azadi), İran’ın başkenti Tahran’da bulunan ve şehrin simgelerinden biri olan önemli bir anıttır.\r\nEskiden “Şahın Kulesi” olarak anılırken, 1979 İran Devrimi sonrası adı “Azadi” yani Özgürlük Kulesi olarak değiştirilmiştir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Yer\tTahran, İran\r\n🏗️ Yapım Tarihi\t1966\r\n\U0001f9d1‍🎨 Mimar\tHossein Amanat\r\n🏛️ Yapı Tipi\tAnıt ve kültürel merkez\r\nYükseklik\tYaklaşık 45 metre\r\nMalzeme\tBeyaz traverten ve beton\r\n\r\n🏗️ Tasarım ve Mimari Özellikler\r\nİran’ın geleneksel mimarisini modern unsurlarla birleştirir.\r\n\r\nKubbe ve kemerlerde İslam ve Pers motifleri yer alır.\r\n\r\nYapı, hem geçmişe saygı hem de modern İran’ın sembolü olarak tasarlanmıştır.\r\n\r\nKule, bir kapı (portal) formundadır; “giriş” ve “özgürlük” kavramını temsil eder.\r\n\r\n🕰️ Tarihçesi ve Önemi\r\n1966’da, İran’ın 2500. yıl dönümünü kutlamak için inşa edilmiştir.\r\n\r\nİlk adı “Şahın Kulesi” idi; Şah Rıza Pehlevi döneminde yapılmıştır.\r\n\r\n1979’da İran Devrimi’nden sonra adı Azadi Kulesi olarak değiştirilmiştir.\r\n\r\nKule, hem İran’ın tarihini hem özgürlük ve ulusal kimliğini sembolize eder.\r\n\r\n🎨 Kültürel ve Sosyal Rolü\r\nGünümüzde Tahran’da turistik ve kültürel merkez olarak işlev görür.\r\n\r\nKule içinde müzeler ve sergi alanları bulunur.\r\n\r\nİran’ın önemli günlerinde ve etkinliklerinde ışıklandırılır ve ziyaret edilir.\r\n\r\n\U0001f9ed Konum ve Çevresi\r\nTahran’ın batısında yer alır.\r\n\r\nÇevresinde parklar ve meydanlar bulunur.\r\n\r\nŞehrin önemli bulvarlarından biri olan Azadi Bulvarı buradan geçer.\r\n\r\n\U0001f9e0 İlginç Bilgiler\r\nAzadi Kulesi, İran’ın en yüksek yapı noktalarından biridir.\r\n\r\nMimar Hossein Amanat, projeyi 19 yaşında tasarlamıştır.\r\n\r\nKule, aynı zamanda İran’ın ulusal kimliğinin ve tarihinin simgesi olarak kabul edilir." },
        { "russia", "⛪ Aziz Basil Katedrali Nedir?\r\nAziz Basil Katedrali (Rusça: Собор Василия Блаженного, Sobor Vasiliya Blazhennogo), Rusya’nın Moskova şehrinde, Kızıl Meydan’da yer alan, mimarisiyle dünyaca ünlü bir Ortodoks kilisesidir.\r\nBurası Rus mimarisinin en ikonik yapılarından biridir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Yer\tMoskova, Rusya\r\n🏗️ Yapım Tarihi\t1555 – 1561\r\n\U0001f9d1‍🎨 Mimar\tBarma ve Postnik Yusupov (efsanevi)\r\n🕊️ Din\tRus Ortodoks Kilisesi\r\n🎨 Mimari Tarz\tRus Bizans ve halk mimarisi karışımı\r\n🏛️ Özellik\tÇok renkli soğan kubbeleriyle meşhur\r\n\r\n🕰️ Tarihçesi\r\nKatedral, IV. İvan (Korkunç İvan) tarafından 1555–1561 yılları arasında yaptırıldı.\r\n\r\nAmacı, Kazan Hanlığı’nın fethini kutlamak ve şükran göstermekti.\r\n\r\nKatedralin resmi adı: Aziz Vasili’nin Katedrali ancak halk arasında “Aziz Basil” olarak anılır.\r\n\r\nYapımında farklı küçük kiliselerin birleşimi esas alınmıştır.\r\n\r\n🏛️ Mimari Özellikler\r\nKatedral, dokuz küçük şapelden oluşur:\r\n\r\nOrtada ana şapel (Aziz Basil’in mezarının bulunduğu yer)\r\n\r\nÇevresinde sekiz küçük şapel vardır, her biri farklı azizlere adanmıştır.\r\n\r\nKubbe tasarımları ve renkleri Rus halk sanatlarından ilham almıştır.\r\n\r\nSoğan kubbeleri (onion dome) Rus mimarisinin tipik simgesidir.\r\n\r\nRenkli mozaikler, karmaşık detaylar ve desenlerle süslüdür.\r\n\r\n🎨 Özellikleri ve Semboller\r\nHer kubbe farklı renk ve desende tasarlanmıştır.\r\n\r\nRenkler ve şekiller, cennetin renkli kubbeleri ve Rus ruhunu temsil eder.\r\n\r\nMimari, Rus Ortodoks inancının coşkusunu ve zenginliğini yansıtır.\r\n\r\n\U0001f9ed Konum ve Turistik Önemi\r\nMoskova’nın Kızıl Meydan’ında yer alır.\r\n\r\nUNESCO Dünya Mirası listesindedir.\r\n\r\nYılda milyonlarca turist tarafından ziyaret edilir.\r\n\r\nRusya’nın ve Moskova’nın en çok tanınan simgelerinden biridir." },
        { "germany", "⛪ Köln Katedrali Nedir?\r\nKöln Katedrali, Almanya’nın Köln şehrinde bulunan, gotik mimarinin başyapıtlarından biri olan büyük bir Katolik katedralidir.\r\nAvrupa’nın en büyük katedrallerinden ve UNESCO Dünya Mirası listesinde yer alır.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Yer\tKöln, Almanya\r\n🏗️ İnşa Başlangıcı\t1248\r\n🏁 Tamamlanma\t1880 (yaklaşık 632 yıl süren inşaat)\r\n\U0001f9d1‍🎨 Mimarlar\tMaster Gerhard (başlangıç), sonra birçok mimar\r\n🎨 Mimari Tarz\tGotik\r\n🏛️ Yükseklik\tYaklaşık 157 metre (dünyanın en yüksek ikinci kilisesi)\r\n⚖️ Ağırlık\tYaklaşık 350.000 ton\r\n\r\n🕰️ Tarihçesi\r\nİnşaat 1248’de başladı ancak ekonomik ve siyasi nedenlerle yüzyıllarca durdu.\r\n\r\nyüzyılda Almanya’nın birleşme heyecanıyla inşaat tamamlandı.\r\n\r\n1880’de biten katedral, Orta Çağ gotik mimarisinin modern dönemde tamamlanmış en büyük örneğidir.\r\n\r\n🏛️ Mimari Özellikler\r\nİki büyük kuleye sahiptir, her biri 157 metre yüksekliğinde.\r\n\r\nKatedralin içi, yüksek tavanları, renkli vitray pencereleri ve detaylı taş işçiliğiyle dikkat çeker.\r\n\r\nKutsal Hazine Odası ve Kutsal Üç Kralın (Müritlerin) kalıntılarını barındıran bir reliği vardır.\r\n\r\n🎯 Önemi ve Fonksiyonu\r\nAlmanya’nın en büyük kilisesidir.\r\n\r\nHristiyanlıkta önemli bir hac merkezidir.\r\n\r\nKöln şehrinin simgesi ve Avrupa’nın mimari başyapıtlarından biridir.\r\n\r\nYıllık milyonlarca turist ve hacı tarafından ziyaret edilir.\r\n\r\n\U0001f9e0 İlginç Bilgiler\r\nKatedral, II. Dünya Savaşı sırasında ağır bombardımanlara maruz kalmış, ancak ayakta kalmayı başarmıştır.\r\n\r\nYapım süresi boyunca birçok mimari tarz ve dönemin teknik özelliklerini yansıtır.\r\n\r\n2006 FIFA Dünya Kupası sırasında Almanya’nın kültürel simgelerinden biri olarak vurgulanmıştır." },
        { "canada", "⛪ Montréal Notre-Dame Bazilikası (Basilique Notre-Dame de Montréal)\r\n📍 Konum:\r\nMontréal, Québec, Kanada\r\n\r\n🏗️ Tarihçe:\r\nİnşaat 1824’te başladı ve 1829’da tamamlandı.\r\n\r\nKanada’nın en eski ve en etkileyici kiliselerinden biridir.\r\n\r\nFransız koloni mirasının önemli bir sembolüdür.\r\n\r\n\U0001f9d1‍🎨 Mimari Tarz:\r\nGotik Revival (Neo-Gotik)\r\n\r\nTasarımcı: James O’Donnell, İrlanda asıllı Amerikalı mimar\r\n\r\nİnce detaylı vitraylar, sivri kemerler, kuleler ve zarif süslemelerle dikkat çeker.\r\n\r\n🏛️ Özellikleri:\r\nİki büyük kuleye sahip (her biri yaklaşık 69 metre yüksekliğinde).\r\n\r\nİç mekan, mavi ve altın renk ağırlıklı, çok zengin süslemelerle kaplı.\r\n\r\nÇok sayıda heykel ve İncil’den sahnelerle dolu vitray pencereler bulunur.\r\n\r\nBüyük orgu (klavsen), Kanada’nın en büyüğü ve en eski orglarından biridir.\r\n\r\n🎨 Önemli Noktalar:\r\nİç mekan özellikle görkemlidir; binlerce küçük detay, heykel ve süsleme içerir.\r\n\r\nHer yıl milyonlarca turist ve yerel cemaat tarafından ziyaret edilir.\r\n\r\n1989’da UNESCO tarafından Montreal’in eski kent bölgesiyle birlikte Dünya Mirası olarak kabul edilmiştir.\r\n\r\n\U0001f9e0 İlginç Bilgiler:\r\n2019’da ünlü Kanadalı pop yıldızı Celine Dion’un düğünü burada gerçekleşmiştir.\r\n\r\nBazilika, ışık ve ses gösterileriyle de ünlüdür; bu gösteriler ziyaretçilere İncil hikayelerini etkileyici biçimde anlatır." },
        { "france", "🗼 Eyfel Kulesi Nedir?\r\nEyfel Kulesi (Fransızca: La Tour Eiffel), Fransa’nın başkenti Paris’te bulunan, dünyanın en tanınmış simgelerinden biridir.\r\n1889 yılında inşa edilmiş ve o zamandan beri Paris’in sembolü olarak kabul edilir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Konum\tParis, Fransa, Seine Nehri kıyısı\r\n🏗️ İnşa Yılı\t1887–1889\r\n👷‍♂️ Mimar\tGustave Eiffel ve ekibi\r\n🏛️ Yapı Türü\tDemir konstrüksiyonlu gözlem kulesi\r\n📏 Yükseklik\t330 metre (antenlerle birlikte)\r\n⚖️ Ağırlık\tYaklaşık 10.100 ton demir\r\n\U0001f6d7 Asansör Sayısı\t5 adet asansör\r\n\r\n🕰️ Tarihçesi\r\n1889 Dünya Fuarı için inşa edildi; fuarın giriş kapısı olarak planlandı.\r\n\r\nBaşlangıçta geçici bir yapı olarak düşünülse de, çok beğenildiği için kalıcı oldu.\r\n\r\nİnşaatı 2 yıl 2 ay gibi kısa bir sürede tamamlandı.\r\n\r\nİlk başta pek çok Parisli ve sanatçı tarafından eleştirilmiş, “Çirkin Demir Yığını” denmişti.\r\n\r\n🏛️ Mimari Özellikler\r\nDemir kafes konstrüksiyon tekniğiyle yapılmıştır.\r\n\r\nÜç katlıdır:\r\n\r\nBirinci ve ikinci katta restoranlar ve alışveriş alanları var.\r\n\r\nÜçüncü kat en yüksek noktadır ve Paris’in panoramik manzarasını sunar.\r\n\r\nKule, rüzgar yüklerini azaltmak için hafif eğimli ve açık kafes yapıda tasarlandı.\r\n\r\n🎯 Önemi ve Fonksiyonu\r\nParis’in ve Fransa’nın simgesidir.\r\n\r\nDünya çapında turizm ikonudur.\r\n\r\nRadyo ve televizyon yayınları için anten barındırır.\r\n\r\nHer yıl yaklaşık 7 milyon kişi tarafından ziyaret edilir.\r\n\r\n\U0001f9e0 İlginç Bilgiler\r\nKule yapıldığı dönemde dünyanın en yüksek yapısıydı (1930’a kadar).\r\n\r\nKule 20.000’den fazla metal parçadan oluşur ve yaklaşık 2.5 milyon vida kullanılmıştır.\r\n\r\nKule her 7 yılda bir yeniden boyanır (yaklaşık 60 ton boya kullanılır).\r\n\r\n2015 yılında kuleye LED aydınlatmalar ve renkli ışıklar eklendi.\r\n\r\n🗺️ Ziyaret Bilgileri\r\nZiyaretçiler asansörle veya merdivenle çıkabilirler (merdivenle çıkış yaklaşık 700 basamaktır)." },
        { "poland", "🏰 Krzyżtopór Sarayı Nedir?\r\nKrzyżtopór Sarayı, Polonya'nın Ujazd kasabasında bulunan, 17. yüzyıldan kalma büyük ve etkileyici bir saray kalıntısıdır.\r\nAvrupa'nın en görkemli barok saraylarından biri olarak kabul edilir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Yer\tUjazd, Polonya\r\n🏗️ İnşa Tarihi\t1627 – 1644\r\n\U0001f9d1‍🎨 Mimar\tMuhtemelen Włoszczowski ailesi için tasarlanmış\r\n🏛️ Mimari Stil\tBarok\r\n🏰 Durumu\tŞu anda harabe halinde, turistik alan olarak ziyaret ediliyor\r\n\r\n🕰️ Tarihçesi\r\nSaray, Krzysztof Ossoliński tarafından yaptırıldı.\r\n\r\nİsmi, ailesinin armasındaki iki haçı (Krzyż) ve kuşu (topór) birleştirir.\r\n\r\nYapımı yaklaşık 17 yıl sürdü ve oldukça lüks ve büyük bir saray olarak tasarlandı.\r\n\r\nyüzyılda Polonya-Litvanya Birliği'nin önemli yapıların biri olarak bilinir.\r\n\r\nZamanla yangınlar ve savaşlar nedeniyle harap oldu.\r\n\r\n🏛️ Mimari ve Özellikleri\r\nSaray, 4 kuleli büyük bir yapıdır.\r\n\r\nMimari planında 365 pencere (yılın günleri sayısı), 52 odası (haftanın günleri), 12 salonu (ayın ayları) ve 4 avlusu (mevsimler) bulunmaktadır.\r\n→ Bu sayıların sembolik anlamları vardır.\r\n\r\nHem savunma hem de konut amaçlı kullanılmıştır.\r\n\r\nİç kısımları zengin süslemelerle donatılmıştır.\r\n\r\n🎯 Önemi\r\nBarok mimarinin ve Rönesans etkilerinin güzel bir örneğidir.\r\n\r\nPolonya tarihinin önemli anıtlarından biridir.\r\n\r\nGünümüzde turistik ziyaretlere açıktır ve kültürel etkinlikler düzenlenmektedir.\r\n\r\n\U0001f9e0 İlginç Bilgiler\r\nSarayın simetrik ve matematiksel planlaması büyük ilgi çekmiştir.\r\n\r\n“365 pencere” efsanesi gerçek olup olmadığı tartışılır ama bu detay turistler arasında popülerdir.\r\n\r\nSarayın büyük bir kısmı zamanla harabeye dönüşmüş, ancak restorasyon çalışmaları devam etmektedir." },
        { "uk", "🕰️ Big Ben Kulesi Nedir?\r\nBig Ben, aslında Londra’daki Palace of Westminster (Parlamento Binası) içindeki büyük saat kulesinin halk arasında yaygın olarak kullanılan adıdır.\r\nAsıl adı Elizabeth Tower’dır.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Yer\tLondra, İngiltere, Westminster\r\n🏗️ İnşa Tarihi\t1843–1859\r\n\U0001f9d1‍🎨 Mimar\tCharles Barry (genel tasarım), Augustus Pugin (detaylar)\r\n⏰ Saat Çapı\tYaklaşık 7 metre\r\n🕰️ Çan Ağırlığı\t13.5 ton (Big Ben adı aslında en büyük saate ait çandır)\r\n🏛️ Yükseklik\t96 metre\r\n🛎️ Saat Mekanizması\tDünyanın en hassas mekanik saatlerinden biri\r\n\r\n🕰️ Tarihçesi\r\n1834’te Parlamento binası yangınla büyük zarar gördü.\r\n\r\nYeni bina ve saat kulesi planlandı.\r\n\r\n1859’da tamamlandı ve ilk kez Big Ben çanı çaldı.\r\n\r\nKule, Kraliçe II. Elizabeth’in tahta çıkışının 60. yılı anısına 2012’de Elizabeth Tower olarak yeniden adlandırıldı.\r\n\r\n🎯 Özellikleri\r\nKule, Neo-Gotik mimarinin güzel bir örneğidir.\r\n\r\nDört tarafında da dev saat yüzleri vardır.\r\n\r\nSaat mekanizması hassas ve elle kurulur.\r\n\r\n“Big Ben” aslında kuledeki en büyük çanın adıdır, fakat halk saat kulesine de bu isimle hitap eder.\r\n\r\n🕰️ Saat ve Çan\r\nSaat her çeyrek saatte Westminster Çanları melodisini çalar.\r\n\r\nBüyük çan (“Big Ben”) ise saat başında uzun bir ton ile çalar.\r\n\r\nSaat mekanizması 150 yıldan uzun süredir çalışıyor.\r\n\r\n\U0001f9e0 İlginç Bilgiler\r\nKule, 2017–2021 yılları arasında kapsamlı bir restorasyon geçirdi.\r\n\r\nSaat yüzü camdan yapılmıştır ve her biri yaklaşık 2.7 metre çapındadır.\r\n\r\nKule, Londra’nın en çok fotoğraflanan yapılarından biridir.\r\n\r\n“Big Ben” adı, bazı kaynaklara göre İngiliz politikacı Sir Benjamin Hall’dan gelmektedir.\r\n\r\n🗺️ Konum\r\nLondra’nın Westminster bölgesinde, Thames Nehri kıyısında.\r\n\r\nParlamento Binası ile birlikte ziyaret edilir.\r\n\r\n" },
        { "brazil", "✝️ İsa Heykeli Nedir?\r\nCristo Redentor, yani Kurtarıcı İsa Heykeli, Brezilya’nın Rio de Janeiro şehrinde bulunan devasa bir heykeldir.\r\nDünyanın en ünlü heykellerinden biridir ve Hristiyanlık sembolü olarak kabul edilir.\r\n\r\n📌 Temel Bilgiler\r\nÖzellik\tAçıklama\r\n📍 Konum\tRio de Janeiro, Corcovado Dağı tepesi\r\n🏗️ İnşa Tarihi\t1922–1931\r\n\U0001f9d1‍🎨 Heykeltraş\tPaul Landowski (Fransız heykeltıraş)\r\n🏛️ Heykel Boyu\tYaklaşık 30 metre (kaide hariç)\r\n🏞️ Tepeden Yükseklik\t710 metre (deniz seviyesinden yüksek)\r\n⚖️ Ağırlık\tYaklaşık 635 ton\r\n\U0001f9f1 Malzeme\tBeton ve taş mozaik (talaş ve çimento karışımı)\r\n\r\n🕰️ Tarihçesi\r\nBrezilya Cumhuriyetinin 100. yıl kutlamaları için yapımına başlandı (1922).\r\n\r\nİnşaat 9 yıl sürdü, 1931’de tamamlandı ve açıldı.\r\n\r\nProje Brezilya Katolik Kilisesi’nin desteğiyle gerçekleşti.\r\n\r\n🎨 Mimari ve Tasarım Özellikleri\r\nİsa figürü kollarını açmış, “barış ve kucaklama” sembolü olarak durur.\r\n\r\nHeykel, Art Deco tarzında tasarlanmıştır.\r\n\r\nYapımı için özel beton karışımı ve taş mozaik kaplama kullanıldı.\r\n\r\nKolları yaklaşık 28 metre açıklığındadır.\r\n\r\n🎯 Önemi ve Semboller\r\nRio’nun ve Brezilya’nın en önemli simgesi.\r\n\r\nHristiyanlık inancının dünyadaki sembollerinden biri.\r\n\r\nBarış, kurtuluş ve insanlığı kucaklama anlamlarını taşır.\r\n\r\n\U0001f9e0 İlginç Bilgiler\r\nHeykel, yıldırım çarpmalarına karşı özel olarak korunmaktadır.\r\n\r\nHer yıl milyonlarca turist ve hacı tarafından ziyaret edilir.\r\n\r\n2007’de Yeni Dünyanın Yedi Harikası arasında seçilmiştir.\r\n\r\nCorcovado Dağı’nın tepesine teleferik ile ulaşılır.\r\n\r\n🗺️ Konum ve Ulaşım\r\nRio’nun merkezinden kolayca ulaşılabilir.\r\n\r\nZiyaretçiler teleferik veya yürüyerek tepeye çıkabilir." },
        { "argentina", "⚽ Arjantin’in Son Dünya Kupası Zaferi\r\n🏆 Turnuva:\r\nFIFA Dünya Kupası 2022\r\n\r\n📍 Yer:\r\nKatar (Middle East - Orta Doğu)\r\n\r\n📅 Tarih:\r\n21 Kasım - 18 Aralık 2022\r\n\r\n🌟 Turnuva Özeti\r\nArjantin, finalde Fransa ile karşılaştı.\r\n\r\nNormal süre 3-3 berabere bitti.\r\n\r\nPenaltı atışlarında Arjantin 4-2 kazandı.\r\n\r\nBu, Arjantin’in tarihindeki 3. Dünya Kupası şampiyonluğu oldu (daha önce 1978 ve 1986’da kazanmıştı).\r\n\r\n🌟 Öne Çıkan Oyuncular\r\nLionel Messi:\r\nTurnuvanın en parlak yıldızı olarak seçildi.\r\nFinal maçında iki gol attı ve genel performansıyla Arjantin’i zafere taşıdı.\r\n\r\nEmiliano Martínez:\r\nKaleci olarak penaltı atışlarında kritik kurtarışlar yaptı.\r\n\r\nÁngel Di María:\r\nFinalde etkili bir performans gösterdi ve gol attı.\r\n\r\n🏅 Ödüller\r\nAltın Top Ödülü: Lionel Messi (Turnuvanın en iyi oyuncusu)\r\n\r\nAltın Eldiven Ödülü: Emiliano Martínez (En iyi kaleci)\r\n\r\n🏟️ Final Maçı Detayları\r\nTarih: 18 Aralık 2022\r\n\r\nYer: Lusail Iconic Stadyumu, Katar\r\n\r\nSkor: Arjantin 3 - 3 Fransa (Penaltılarla 4-2 Arjantin)\r\n\r\nMaç, tarihin en heyecanlı ve dramatik final maçlarından biri olarak kabul edildi.\r\n\r\n🎉 Arjantin İçin Anlamı\r\n36 yıl sonra kazanılan büyük zaferdi (son olarak 1986’da kazanmışlardı).\r\n\r\nLionel Messi’nin kariyerindeki en büyük başarı olarak görülür.\r\n\r\nÜlke çapında büyük kutlamalar ve sevinç yaşandı.\r\n\r\n" },
        // Yeni yapıları buraya ekle!
    };

    public Sprite uaeSprite;
    public Sprite indiaSprite;
    public Sprite turkiyeSprite;
    public Sprite chinaSprite;
    public Sprite italySprite;
    public Sprite spainSprite;
    public Sprite mexicoSprite;
    public Sprite egyptSprite;
    public Sprite usaSprite;
    public Sprite iranSprite;
    public Sprite russiaSprite;
    public Sprite germanySprite;
    public Sprite canadaSprite;
    public Sprite franceSprite;
    public Sprite polandSprite;
    public Sprite ukSprite;
    public Sprite brazilSprite;
    public Sprite argentinaSprite;

    private Dictionary<string, Sprite> structureSprites;

    void Awake()
    {
        // Görselleri yapı isimleriyle eşleştiriyoruz
        structureSprites = new Dictionary<string, Sprite>
        {
            { "uae", uaeSprite },
            { "india", indiaSprite },
            { "turkiye", turkiyeSprite },
            { "china", chinaSprite },
            { "italy", italySprite },
            { "spain", spainSprite },
            { "mexico", mexicoSprite },
            { "egypt", egyptSprite },
            { "usa", usaSprite },
            { "iran", iranSprite },
            { "russia", russiaSprite },
            { "germany", germanySprite },
            { "canada", canadaSprite },
            { "france", franceSprite },
            { "poland", polandSprite },
            { "uk", ukSprite },
            { "brazil", brazilSprite },
            { "argentina", argentinaSprite },

        };
    }

    void Update()
    {
        // Kullanıcı ekrana dokunduğunda çalışır
        if (Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Began)
        {
            Ray ray = arCamera.ScreenPointToRay(Input.GetTouch(0).position);
            if (Physics.Raycast(ray, out RaycastHit hit))
            {
                string objName = hit.transform.name;

                if (structureDescriptions.ContainsKey(objName))
                {
                    // Açıklama metni göster
                    popupText.text = structureDescriptions[objName];

                    // Eğer görsel varsa, göster; yoksa gizle
                    if (structureSprites.TryGetValue(objName, out Sprite sprite))
                    {
                        popupImage.sprite = sprite;
                        popupImage.gameObject.SetActive(true);
                    }
                    else
                    {
                        popupImage.gameObject.SetActive(false);
                    }

                    popupPanel.SetActive(true);
                }
            }
        }
    }

    public void ClosePopup()
    {
        popupPanel.SetActive(false);
    }
}
